In [19]:
import numpy as np

#Ques1-Create a Python list [10, 20, 30, 40] and convert it into a NumPy array.

In [20]:
my_list = [10, 20, 30, 40]
my_array = np.array(my_list)

print(my_array)

[10 20 30 40]


# Ques2-Print its type().

In [21]:
my_list = [10, 20, 30, 40]
my_array = np.array(my_list)
print(my_array)
print(type(my_array))

[10 20 30 40]
<class 'numpy.ndarray'>


# Ques3-Multiply the whole array by 2 in a single line (no loop) and print the result.

In [22]:
my_list = [10, 20, 30, 40]
my_array = np.array(my_list)

print(my_array * 2)

[20 40 60 80]


# Ques4-Create a 4×4 identity matrix.

In [23]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Ques5-Create a 3×3 array of random integers between 1 and 50.

In [24]:
random_array = np.random.randint(1, 51, size=(3, 3))
print(random_array)

[[32 14 31]
 [23 13 42]
 [39 32 35]]


# Ques6-Create an array of 15 evenly spaced numbers between 0 and 100 using linspace.

In [25]:
arr = np.linspace(0, 100, 15)
print(arr)

[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


# Ques7-Create a 2×3 array of floats. Convert it to int64 and observe the truncation.

In [26]:
arr = np.array([[1.5, 2.9, 3.2],
                [4.7, 5.1, 6.8]])
print("Original float array:")
print(arr)
arr = arr.astype(np.int64)
print("After converting to int64:")
print(arr)

Original float array:
[[1.5 2.9 3.2]
 [4.7 5.1 6.8]]
After converting to int64:
[[1 2 3]
 [4 5 6]]


# Ques8-Print ndim, shape, size and dtype of a 4-D array created with np.arange(16).reshape(2,2,2,2)

In [27]:
arr = np.arange(16).reshape(2, 2, 2, 2)

print("Array:")
print(arr)
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Number of dimensions: 4
Shape: (2, 2, 2, 2)
Size: 16
Data type: int64


# Ques9-Create two 3×3 arrays. Compute their element-wise product and their matrix product, and explain the difference to your neighbor.

In [28]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Element-wise product:")
print(a * b)
print("Matrix product:")
print(a @ b)

Element-wise product:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Ques10-Create an array [5, 10, 15, 20] and use a relational operator to get a Boolean array of which elements are greater than 10.

In [29]:
arr = np.array([5, 10, 15, 20])
result = arr > 10
print(result)

[False False  True  True]


# Ques11-Given a 4×4 array of random integers, find the row with the maximum sum.

In [30]:
import numpy as np

arr = np.random.randint(1, 50, (4, 4))

print(arr)

row_sum = arr.sum(axis=1)

print("Row sums:", row_sum)
print("Maximum row:", np.argmax(row_sum) + 1)

[[48  7 21 27]
 [35 45 31  3]
 [16 32 40 21]
 [14 38  2 25]]
Row sums: [103 114 109  79]
Maximum row: 2
